### PR TITLE
#154127957 add CRUD operations for events

### PR DESCRIPTION
**Pull request by paulrimiru**
#### What does this PR do?
This PR adds functionality to allow users to register, login and  perform CRUD operations on Events
#### Description of Task to be completed?
* add functionality to allow users to perform CRUD operations on events
#### How should this be manually tested?
* This can manually be tested by running the application locally using 
  http://127.0.0.1:5000/flasky/ 
  as the root url
* The API can be manually tested Swagger documentation
[Bright Event Documentation](https://paul-bright-events.herokuapp.com/apidocs)
#### Any background context you want to provide?
Before this PR users did not have a persistent events data to manipulate
#### What are the relevant pivotal tracker stories?
#154127957 add CRUD operations for events

### CODE REVIEW

**Review by younggeeks — COMMENTED** [review]
Improve your docstring comments

**Review by younggeeks — COMMENTED** [review]
resp = requests.post("http://127.0.0.1:5000/api/v1/events", json=event_data).json()

http://127.0.0.1:5000
Won't this be a problem when your root  URL changes?

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Comment by paulrimiru** [comment]
Thanks, I am not sure but i will do more research on it.

**Pull request merged**
